{% set name = "jupyter_server" %}
{% set version = "1.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f0c75e0a577536125ad62a442ebb7cf02746f1a69d907e8a273c6225d281237

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main

requirements:
  host:
    - python
    - pip
    - jupyter-packaging >=0.9,<2
  run:
    - python
    - ipython_genutils
    - jinja2
    - jupyter_core >=4.6.0
    - jupyter_client >=6.1.1
    - nbconvert
    - nbformat
    - pyzmq >=17
    - argon2-cffi
    - send2trash
    - terminado >=0.8.3
    - tornado >=6.1
    - traitlets >=4.2.1
    - prometheus_client
    - anyio>=3.1.0,<4
    - websocket-client

test:
  requires:
    - pip
  commands:
    - pip check
    - jupyter server -h
  imports:
    - jupyter_server

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Jupyter Server
  description: The Jupyter Server provides the backend for Jupyter web applications such as the Jupyter notebook and JupyterLab.
  dev_url: https://github.com/jupyter/jupyter_server
  doc_url: https://jupyter-server.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
    - bollwyvl
    - Zsailer
